const item = [
  {
    name: "Sugar",
    description: " it is the best ",
    image: "./${product.name}.webp",
    info: "1 Kg",
    category: "grocery",
    price: 20,
    mrp: 100,
  },
  {
    name: "Sooji",
    description: " it is the best ",
    image: "./${product.name}.webp",
    info: "1 Kg",
    category: "grocery",
    price: 30,
    mrp: 100,
  },
  {
    name: "Atta",
    description: " it is the best ",
    image: "./${product.name}.webp",
    info: "1 Kg",
    category: "grocery",
    price: 40,
    mrp: 100,
  },
  {
    name: "Maida",
    description: " it is the best ",
    image: "./${product.name}.webp",
    info: "1 Kg",
    category: "grocery",
    price: 50,
    mrp: 100,
  },
  {
    name: "Sunrich Oil",
    description: " it is the best ",
    image: "./${product.name}.webp",
    info: "1 Kg",
    category: "grocery",
    price: 60,
    mrp: 100,
  },
  {
    name: "Saffola Oil",
    description: " it is the best ",
    image: "./${product.name}.webp",
    info: "1 Kg",
    category: "grocery",
    price: 70,
    mrp: 100,
  },
  {
    name: "Fortune Oil",
    description: " it is the best ",
    image: "./${product.name}.webp",
    info: "1 Kg",
    category: "grocery",
    price: 70,
    mrp: 100,
  },
  {
    name: "Gemini Oil",
    description: " it is the best ",
    image: "./${product.name}.webp",
    info: "1 Kg",
    category: "grocery",
    price: 70,
    mrp: 100,
  },
  {
    name: "Gowardhan Ghee",
    description: " it is the best ",
    image: "./${product.name}.webp",
    info: "1 Kg",
    category: "grocery",
    price: 70,
    mrp: 100,
  },
  {
    name: "Madhur Sugar",
    description: " it is the best ",
    image: "./${product.name}.webp",
    info: "1 Kg",
    category: "grocery",
    price: 70,
    mrp: 100,
  },
  {
    name: "School Supplies",
    description: " it is the best ",
    image: "./${product.name}.webp",
    info: "1 Kg",
    category: "grocery",
    price: 70,
    mrp: 100,
  },
  {
    name: "Tata Salt",
    description: " it is the best ",
    image: "./${product.name}.webp",
    info: "1 Kg",
    category: "grocery",
    price: 40,
    mrp: 100,
  },
  {
    name: "Aashirvaad Atta",
    description: " it is the best ",
    image: "./${product.name}.webp",
    info: "1 Kg",
    category: "grocery",
    price: 40,
    mrp: 100,
  },
  {
    name: "Aashirvaad Atta",
    description: " it is the best ",
    image: "./${product.name}.webp",
    info: "10 Kg",
    category: "grocery",
    price: 40,
    mrp: 100,
  },
  {
    name: "Atta",
    description: " it is the best ",
    image: "./${product.name}.webp",
    info: "10 Kg",
    category: "grocery",
    price: 40,
    mrp: 100,
  },
  {
    name: "India Gate",
    description: " it is the best ",
    image: "./${product.name}.webp",
    info: "5 Kg",
    category: "grocery",
    price: 40,
    mrp: 100,
  },
  {
    name: "Daawat Rice",
    description: " it is the best ",
    image: "./${product.name}.webp",
    info: "1 Kg",
    category: "grocery",
    price: 40,
    mrp: 100,
  },
  {
    name: "Suffola Gold",
    description: " it is the best ",
    image: "./${product.name}.webp",
    info: "1 Ltr",
    category: "grocery",
    price: 40,
    mrp: 100,
  },
  {
    name: "Gemini Groundnut Oil",
    description: " it is the best ",
    image: "./${product.name}.webp",
    info: "1 Ltr",
    category: "grocery",
    price: 40,
    mrp: 100,
  },
  {
    name: "Dhara Groundnut Oil",
    description: " it is the best ",
    image: "./${product.name}.webp",
    info: "1 Ltr",
    category: "grocery",
    price: 40,
    mrp: 100,
  },
  {
    name: "Maggi Masala",
    description: " it is the best ",
    image: "./${product.name}.webp",
    info: "1 Ltr",
    category: "vks_grocery",
    price: 40,
    mrp: 100,
  },
  {
    name: "Everest Tikhalal Powder",
    description: " it is the best ",
    image: "./${product.name}.webp",
    info: "",
    category: "vks_grocery",
    price: 40,
    mrp: 100,
  },
  {
    name: "Vandevi Hing Powder",
    description: " it is the best ",
    image: "./${product.name}.webp",
    info: "",
    category: "vks_grocery",
    price: 40,
    mrp: 100,
  },
  {
    name: "Chings Paneer Chilli Masala",
    description: " it is the best ",
    image: "./${product.name}.webp",
    info: "",
    category: "vks_grocery",
    price: 40,
    mrp: 100,
  },
  {
    name: "LG Hing powder",
    description: " it is the best ",
    image: "./${product.name}.webp",
    info: "",
    category: "vks_grocery",
    price: 40,
    mrp: 100,
  },
  {
    name: "Everest Kitchen King Masala",
    description: " it is the best ",
    image: "./${product.name}.webp",
    info: "10 Kg",
    category: "vks_grocery",
    price: 40,
    mrp: 100,
  },
  {
    name: "Everest Sambhar Masala",
    description: " it is the best ",
    image: "./${product.name}.webp",
    info: "10 Kg",
    category: "vks_grocery",
    price: 40,
    mrp: 100,
  },
  {
    name: "Everest Sabji Masala",
    description: " it is the best ",
    image: "./${product.name}.webp",
    info: "10 Kg",
    category: "vks_grocery",
    price: 40,
    mrp: 100,
  },
  {
    name: "Everest Turmeric Powder",
    description: " it is the best ",
    image: "./${product.name}.webp",
    info: "",
    category: "vks_grocery",
    price: 40,
    mrp: 100,
  },
  {
    name: "Chings Veg Manchurian Masala",
    description: " it is the best ",
    image: "./${product.name}.webp",
    info: "10 Kg",
    category: "vks_grocery",
    price: 40,
    mrp: 100,
  },
  {
    name: "Nutrela Soya Chunks Box",
    description: " it is the best ",
    image: "./${product.name}.webp",
    info: "10 Kg",
    category: "vks_grocery",
    price: 40,
    mrp: 100,
  },
  {
    name: "Nutrela Soya Chunks",
    description: " it is the best ",
    image: "./${product.name}.webp",
    info: "10 Kg",
    category: "vks_grocery",
    price: 40,
    mrp: 100,
  },
  {
    name: "Cashew",
    description: " it is the best ",
    image: "./${product.name}.webp",
    info: "10 Kg",
    category: "packaged_food",
    price: 40,
    mrp: 100,
  },
  {
    name: "Dynamix Cow Ghee ",
    description: " it is the best ",
    image: "./${product.name}.webp",
    info: "10 Kg",
    category: "packaged_food",
    price: 40,
    mrp: 100,
  },
  {
    name: "Bourbon Biscuit",
    description: " it is the best ",
    image: "./${product.name}.webp",
    info: "10 Kg",
    category: "packaged_food",
    price: 40,
    mrp: 100,
  },
  {
    name: "Parle Gold Biscuit",
    description: " it is the best ",
    image: "./${product.name}.webp",
    info: "10 Kg",
    category: "packaged_food",
    price: 40,
    mrp: 100,
  },
  {
    name: "Hide & Seek Biscuit",
    description: " it is the best ",
    image: "./${product.name}.webp",
    info: "10 Kg",
    category: "packaged_food",
    price: 40,
    mrp: 100,
  },
  {
    name: "Nutri Choice Biscuit",
    description: " it is the best ",
    image: "./${product.name}.webp",
    info: "10 Kg",
    category: "packaged_food",
    price: 40,
    mrp: 100,
  },
  {
    name: "Gooday Biscuit",
    description: " it is the best ",
    image: "./${product.name}.webp",
    info: "10 Kg",
    category: "packaged_food",
    price: 40,
    mrp: 100,
  },
  {
    name: "Krack Jack Biscuit",
    description: " it is the best ",
    image: "./${product.name}.webp",
    info: "10 Kg",
    category: "packaged_food",
    price: 40,
    mrp: 100,
  },
  {
    name: "Maggi Masala Noodles",
    description: " it is the best ",
    image: "./${product.name}.webp",
    info: "10 Kg",
    category: "packaged_food",
    price: 40,
    mrp: 100,
  },
  {
    name: "Maggi Masala Noodles 8 Pack",
    description: " it is the best ",
    image: "./${product.name}.webp",
    info: "10 Kg",
    category: "packaged_food",
    price: 40,
    mrp: 100,
  },
  {
    name: "Maggi Paazta Macroni",
    description: " it is the best ",
    image: "./${product.name}.webp",
    info: "10 Kg",
    category: "packaged_food",
    price: 40,
    mrp: 100,
  },
  {
    name: "Maggi Veg Atta Noodles 8 Pack",
    description: " it is the best ",
    image: "./${product.name}.webp",
    info: "10 Kg",
    category: "packaged_food",
    price: 40,
    mrp: 100,
  },
  {
    name: "Chings Hakka Noodles",
    description: " it is the best ",
    image: "./${product.name}.webp",
    info: "10 Kg",
    category: "packaged_food",
    price: 40,
    mrp: 100,
  },
  {
    name: "Maggi Veg Atta Noodles",
    description: " it is the best ",
    image: "./${product.name}.webp",
    info: "10 Kg",
    category: "packaged_food",
    price: 40,
    mrp: 100,
  },
  {
    name: "Red Label",
    description: " it is the best ",
    image: "./${product.name}.webp",
    info: "10 Kg",
    category: "beverages",
    price: 40,
    mrp: 100,
  },
  {
    name: "Red Label Natural Care",
    description: " it is the best ",
    image: "./${product.name}.webp",
    info: "10 Kg",
    category: "beverages",
    price: 40,
    mrp: 100,
  },
  {
    name: "Tata Agni Tea",
    description: " it is the best ",
    image: "./${product.name}.webp",
    info: "10 Kg",
    category: "beverages",
    price: 40,
    mrp: 100,
  },
  {
    name: "Society Tea Powder",
    description: " it is the best ",
    image: "./${product.name}.webp",
    info: "10 Kg",
    category: "beverages",
    price: 40,
    mrp: 100,
  },
  {
    name: "Tata Gold Tea",
    description: " it is the best ",
    image: "./${product.name}.webp",
    info: "10 Kg",
    category: "beverages",
    price: 40,
    mrp: 100,
  },
  {
    name: "Sprite",
    description: " it is the best ",
    image: "./${product.name}.webp",
    info: "10 Kg",
    category: "beverages",
    price: 40,
    mrp: 100,
  },
  {
    name: "Mirinda",
    description: " it is the best ",
    image: "./${product.name}.webp",
    info: "10 Kg",
    category: "beverages",
    price: 40,
    mrp: 100,
  },
  {
    name: "Thumps Up",
    description: " it is the best ",
    image: "./${product.name}.webp",
    info: "10 Kg",
    category: "beverages",
    price: 40,
    mrp: 100,
  },
  {
    name: "Sprite 600ml",
    description: " it is the best ",
    image: "./${product.name}.webp",
    info: "10 Kg",
    category: "beverages",
    price: 40,
    mrp: 100,
  },
  {
    name: "Nescafe Coffee",
    description: " it is the best ",
    image: "./${product.name}.webp",
    info: "10 Kg",
    category: "beverages",
    price: 40,
    mrp: 100,
  },
  {
    name: "Nescafe Coffee 90gm",
    description: " it is the best ",
    image: "./${product.name}.webp",
    info: "10 Kg",
    category: "beverages",
    price: 40,
    mrp: 100,
  },
  {
    name: "Nescafe Coffee 24gm",
    description: " it is the best ",
    image: "./${product.name}.webp",
    info: "10 Kg",
    category: "beverages",
    price: 40,
    mrp: 100,
  },
  {
    name: "Sunrise Coffee",
    description: " it is the best ",
    image: "./${product.name}.webp",
    info: "10 Kg",
    category: "beverages",
    price: 40,
    mrp: 100,
  },
  {
    name: "Bournvita 1 Kg",
    description: " it is the best ",
    image: "./${product.name}.webp",
    info: "10 Kg",
    category: "beverages",
    price: 40,
    mrp: 100,
  },
  {
    name: "Bournvita 750 gm",
    description: " it is the best ",
    image: "./${product.name}.webp",
    info: "10 Kg",
    category: "beverages",
    price: 40,
    mrp: 100,
  },
  {
    name: "Bournvita 200 gm",
    description: " it is the best ",
    image: "./${product.name}.webp",
    info: "10 Kg",
    category: "beverages",
    price: 40,
    mrp: 100,
  },
  {
    name: "Bournvita",
    description: " it is the best ",
    image: "./${product.name}.webp",
    info: "10 Kg",
    category: "beverages",
    price: 40,
    mrp: 100,
  },
  {
    name: "Parachute Oil 300 ml",
    description: " it is the best ",
    image: "./${product.name}.webp",
    info: "10 Kg",
    category: "personal_care",
    price: 40,
    mrp: 100,
  },
  {
    name: "Parachute Oil 600 ml",
    description: " it is the best ",
    image: "./${product.name}.webp",
    info: "10 Kg",
    category: "personal_care",
    price: 40,
    mrp: 100,
  },
  {
    name: "Parachute Oil",
    description: " it is the best ",
    image: "./${product.name}.webp",
    info: "10 Kg",
    category: "personal_care",
    price: 40,
    mrp: 100,
  },
  {
    name: "Clinic Plus",
    description: " it is the best ",
    image: "./${product.name}.webp",
    info: "10 Kg",
    category: "personal_care",
    price: 40,
    mrp: 100,
  },
  {
    name: "Dove Shampoo",
    description: " it is the best ",
    image: "./${product.name}.webp",
    info: "10 Kg",
    category: "personal_care",
    price: 40,
    mrp: 100,
  },
  {
    name: "Head & Shoulder",
    description: " it is the best ",
    image: "./${product.name}.webp",
    info: "10 Kg",
    category: "personal_care",
    price: 40,
    mrp: 100,
  },
  {
    name: "Bajaj Almond Oil",
    description: " it is the best ",
    image: "./${product.name}.webp",
    info: "10 Kg",
    category: "personal_care",
    price: 40,
    mrp: 100,
  },
  {
    name: "Godrej Hair Color",
    description: " it is the best ",
    image: ".Images/${product.name}.webp",
    info: "10 Kg",
    category: "personal_care",
    price: 40,
    mrp: 100,
  },
];

module.exports = { data: item };
